 
    <tit_1>T&eacute;rminos y condiciones</tit_1> </br></br>  
    <p>El acceso a este Sitio y la utilizaci&oacute;n de sus servicios est&aacute; sujeto a los t&eacute;rminos y condiciones generales que se establecen a continuaci&oacute;n, y a las de &iacute;ndole particular que aparecen en sus anexos o en las carteleras de una determinada p&aacute;gina del mismo (los "T&eacute;rminos y Condiciones") De continuar Ud. (el "Usuario") la visita de este Sitio, se entender&aacute; que presta su conformidad con los T&eacute;rminos y Condiciones.</p></br>
    <p>Estos T&eacute;rminos y Condiciones est&aacute;n sujetos a modificaciones, las que entrar&aacute;n en vigencia a partir del momento en que sean publicadas en este Sitio o notificadas al Usuario, lo que ocurra primero.</p></br>
    <tit_3>Servicio</tit_3></br></br> 
    <p>&eacute;ste consiste en un medio de informaci&oacute;n, publicidad y comunicaciones on-line provisto por la C&aacute;mara Argentina de Comercio Electr&oacute;nico, de aqu&iacute; en adelante "GEZZI", y supone la aceptaci&oacute;n por el Usuario de estos T&eacute;rminos y Condiciones.</p></br>
    <p>La informaci&oacute;n contenida en el Sitio proviene de varias fuentes. Dicha informaci&oacute;n no puede considerarse exhaustiva, completa, o que satisfar&aacute; todas las necesidades del Usuario. En su gran mayor&iacute;a, esa informaci&oacute;n est&aacute; meramente destinada a permitir al Usuario el acceso a una mayor cantidad de datos sobre el tema de su inter&eacute;s, siendo que algunos contenidos pueden ser provistos por terceros, sin un efectivo control por parte del GEZZI, por lo que se sugiere al Usuario que lea con especial cuidado estos T&eacute;rminos y Condiciones.</p></br>
    <tit_3>Responsabilidad por la Informaci&oacute;n contenida en el Servicio</tit_3></br></br>
    <p>GEZZI no se responsabiliza por los da&ntilde;os y perjuicios que pudiera ocasionar el uso de la informaci&oacute;n que provee el Servicio.</p></br>
    <p>GEZZI no garantiza la veracidad o vigencia de esa informaci&oacute;n, ni que dicha informaci&oacute;n no haya sido alterada, luego de su inserci&oacute;n en el Sitio.</p></br>
    <p>En caso que el Usuario se sienta agraviado o perjudicado por esa informaci&oacute;n, deber&aacute; dirigir su acci&oacute;n exclusivamente contra el Proveedor de la misma. En tal supuesto, a pedido del Usuario, GEZZI pondr&aacute; a su disposici&oacute;n, en la medida que los posea, los datos necesarios para que pueda hacer su reclamo.</p></br>
    <p>GEZZI tampoco se responsabiliza por: (i) la inviolabilidad de la transmisi&oacute;n de los datos cursados por las redes p&uacute;blicas de telecomunicaciones, o por cualquier otro medio telem&aacute;tico, o de los mensajes que el Usuario curse con otros Usuarios en su caso.</p></br>
    <tit_3>Responsabilidad sobre enlaces</tit_3></br></br>
    <p>GEZZI puede facilitar enlaces, websites o servicios de otras compa&ntilde;&iacute;as a trav&eacute;s de su/s Sitio/s, as&iacute; como facilitar al Usuario de su Sitio web, la descarga de softwares de terceros. El Usuario entiende y acepta que GEZZI no controla y no es responsable de estos servicios y productos.</p></br>
    <p>El Usuario del Sitio acepta y reconoce que GEZZI no controla, ni supervisa, ni asume responsabilidad alguna por la calidad, seguridad, caracter&iacute;sticas y dem&aacute;s elementos de los productos y/o servicios promocionados u ofrecidos por terceros en su Sitio web.</p></br>
    <tit_3>Responsabilidad por Downloads (descargas)</tit_3></br></br>
    <p>Corre por cuenta del Usuario el verificar la inexistencia de virus en los programas y materiales que el Usuario descargue en su equipo. En ning&uacute;n caso el Titular ser&aacute; responsable por los da&ntilde;os causados por elementos destructivos que pudieran haber introducido terceros a los materiales de download provistos por GEZZI, ni por los materiales de download suministrados por los Proveedores de Informaci&oacute;n o un tercero sin autorizaci&oacute;n expresa de GEZZI.</p></br>
    <tit_3>Sitios Vinculados</tit_3></br></br>
    <p>El Usuario reconoce que ni GEZZI ni los Proveedores de Informaci&oacute;n tienen control alguno sobre otros sitios a los que puede acceder a trav&eacute;s de links u otro tipo de vinculaci&oacute;n telem&aacute;tica (los Sitios Vinculados) Por lo tanto ninguno de ellos se hace responsable por el contenido de los Sitios Vinculados.</p></br>
    <tit_3>Varios</tit_3></br></br>
    <p><strong>1.	Licencias de Software.</strong> GEZZI y los Proveedores de Informaci&oacute;n conceden al Usuario una licencia de uso intransferible, no exclusiva y revocable para utilizar los materiales de download.</p></br>
    <p><strong>2.	Equipamiento.</strong> GEZZI no est&aacute; obligado a proveer ning&uacute;n equipo o programa de software para acceder al Servicio. El Usuario deber&aacute; contar con todo los recursos necesarios para ello, incluidos los de telecomunicaciones.</p></br>
    <p><strong>3.	Pol&iacute;tica de Uso del Servicio. </strong>El Usuario acepta la Pol&iacute;tica de Uso del Servicio establecida en el presente, y sus modificaciones. GEZZI se reserva el derecho de eliminar o modificar cualquier informaci&oacute;n, comunicaci&oacute;n, material de download, o mensaje que en su opini&oacute;n viole la Pol&iacute;tica de Uso.</p></br>
    <p><strong>4.	Derechos de Autor.</strong> La informaci&oacute;n contenida en el Sitio puede ser propiedad intelectual del GEZZI, de los Proveedores de Informaci&oacute;n o de un tercero. La informaci&oacute;n y los materiales de download s&oacute;lo podr&aacute;n ser utilizados con fines no comerciales.</p></br>
    <p><strong>5.</strong>	La retransmisi&oacute;n o publicaci&oacute;n de cualquier material se encuentra prohibida sin el previo consentimiento escrito de su autor. En los casos en que se autorice, el Usuario deber&aacute; citar al autor y no podr&aacute; modificar este material.</p></br>
    <p><strong>6.	Control de Contenidos.</strong> GEZZI no controla las comunicaciones y materiales que los Usuarios o Proveedores de Informaci&oacute;n ingresan al sitio. GEZZI no se hace responsable por el contenido de estas comunicaciones y materiales, sin perjuicio de lo cual se reserva el derecho de bloquear el acceso o de eliminar cualquier comunicaci&oacute;n o material que considere (a) abusivo, difamatorio, obsceno, falso o enga&ntilde;oso, (b) violatorio de derechos de propiedad intelectual de un tercero o (c) violatorio de las disposiciones de la Pol&iacute;tica de Uso del Servicio.</p></br>
    <p><strong>7.	Compromiso de Indemnidad.</strong> El Usuario se obliga a mantener indemne a GEZZI, sus dependientes, licenciantes, proveedores y licenciatarios de los da&ntilde;os resultantes (incluyendo los costos de defensa) de cualquier acto o hecho il&iacute;cito imputable al Usuario o a un tercero que utilice la cuenta del Usuario. GEZZI podr&aacute; variar, eliminar y/o agregar t&eacute;rminos y/o condiciones en cualquiera de las cl&aacute;usulas del presente contrato, sin la previa conformidad del Usuario. El Usuario se hace exclusivo responsable por la confidencialidad y el uso de su contrase&ntilde;a, como as&iacute; tambi&eacute;n por las instrucciones que se ejecuten en su nombre a partir de la utilizaci&oacute;n del sistema.</p></br>
    <p><strong>8.	Jurisdicci&oacute;n y Ley Aplicable.</strong> Toda cuesti&oacute;n entre GEZZI y el Usuario estar&aacute; regida por las leyes de la Rep&uacute;blica Argentina, con exclusi&oacute;n de toda norma que remita a la aplicaci&oacute;n de una ley extranjera. Cualquier controversia ser&aacute; sometida a los Tribunales Ordinarios en lo Comercial de la Capital Federal.</p></br>
    <p><strong>9.	Renuncias.</strong> La demora u omisi&oacute;n de GEZZI en exigir el estricto cumplimiento de estos T&eacute;rminos y Condiciones no podr&aacute; interpretarse como renuncia a sus derechos.</p></br>
    <p><strong>10.	Nulidad parcial.</strong> En caso que alguna disposici&oacute;n de estos T&eacute;rminos y Condiciones fuera declarada nula, ello no afectar&aacute; la validez de las dem&aacute;s.</p></br>
    <p><strong>11.	Marcas.</strong> GEZZI es una marca registrada de la C&aacute;mara Argentina de Comercio Electr&oacute;nico. Toda otra marca o logotipo que aparezca en el Sitio pertenece a GEZZI o a terceros y el Usuario no podr&aacute; utilizarlas sin autorizaci&oacute;n de su propietario.</p></br>
    <p><strong>12.	Notificaciones.</strong> Las notificaciones al Usuario podr&aacute;n cursarse por (i) correo electr&oacute;nico, (ii) por nota enviada por correo al domicilio legal de GEZZI en el presente.</p></br>